#!/bin/bash

echo "Welcome to FLIC - FLoflis Iso Creator"
echo "----"

echo "Installing dependencies..."
sudo apt-get install -y kpartx zip xz-utils qemu qemu-user-static binfmt-support

#- detect first use
#- only install dependencies if first use
#- subcommand to start working at an ISO - detect if it is .zip (unzip filename) or .xz (unxz -k filename)
#- extract, and only accept .img file (clone the .img file and then: sudo kpartx -av filename.img)
#- ls /dev/mapper

#- sudo mkdir /mnt/flictmp
#- sudo mount -t ext4 -o loop /dev/mapper/loop13p2 /mnt/flictmp
#- ls /mnt/flictmp
#- sudo cp /usr/bin/qemu-arm-static /mnt/flictmp/usr/bin (or qemu-aarch64-static or qemu-riscv64-static)
#- if Ubuntu arm64: sudo rm -f /mnt/flictmp/etc/resolv.conf sudo cp /etc/resolv.conf /mnt/flictmp/etc
#- cd /mnt/flictmp
#- sudo mount --bind /dev dev/
#- sudo mount --bind /sys sys/
#- sudo mount --bind /proc proc/
#- sudo mount --bind /dev/pts dev/pts
#- sudo chroot . bin/bash
#- sudo umount /mnt/flictmp
#- sudo zip filename-date.zip filename-date.img
#- sudo losetup -d /dev/loop0 ??

#- extras
#- sudo dd if=/dev/zero bs=1M count=2048 >> filename.img (increases img size)
#- sudo losetup -f -P --show filename.img
